// Code generated by MockGen. DO NOT EDIT.
// Source: zerotrust_chat/crypto/rsa (interfaces: PrivateKey)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	rsa "zerotrust_chat/crypto/rsa"

	gomock "github.com/golang/mock/gomock"
)

// MockPrivateKey is a mock of PrivateKey interface.
type MockPrivateKey struct {
	ctrl     *gomock.Controller
	recorder *MockPrivateKeyMockRecorder
}

// MockPrivateKeyMockRecorder is the mock recorder for MockPrivateKey.
type MockPrivateKeyMockRecorder struct {
	mock *MockPrivateKey
}

// NewMockPrivateKey creates a new mock instance.
func NewMockPrivateKey(ctrl *gomock.Controller) *MockPrivateKey {
	mock := &MockPrivateKey{ctrl: ctrl}
	mock.recorder = &MockPrivateKeyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrivateKey) EXPECT() *MockPrivateKeyMockRecorder {
	return m.recorder
}

// Decrypt mocks base method.
func (m *MockPrivateKey) Decrypt(arg0 string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decrypt", arg0)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decrypt indicates an expected call of Decrypt.
func (mr *MockPrivateKeyMockRecorder) Decrypt(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decrypt", reflect.TypeOf((*MockPrivateKey)(nil).Decrypt), arg0)
}

// GetLabel mocks base method.
func (m *MockPrivateKey) GetLabel() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLabel")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GetLabel indicates an expected call of GetLabel.
func (mr *MockPrivateKeyMockRecorder) GetLabel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLabel", reflect.TypeOf((*MockPrivateKey)(nil).GetLabel))
}

// GetPublicKey mocks base method.
func (m *MockPrivateKey) GetPublicKey() rsa.PublicKey {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicKey")
	ret0, _ := ret[0].(rsa.PublicKey)
	return ret0
}

// GetPublicKey indicates an expected call of GetPublicKey.
func (mr *MockPrivateKeyMockRecorder) GetPublicKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicKey", reflect.TypeOf((*MockPrivateKey)(nil).GetPublicKey))
}
